<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>WhisperWind.App</RootNamespace>
    <AssemblyName>WhisperWind</AssemblyName>
    <ApplicationIcon></ApplicationIcon>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WhisperWind.Core\WhisperWind.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.2" />
    <PackageReference Include="WPF-UI" Version="3.0.3" />
    <PackageReference Include="H.InputSimulator" Version="1.6.0" />
  </ItemGroup>

</Project>
